### PR TITLE
Fix for https://github.com/sile/libflate/issues/52

### PR DESCRIPTION
**Pull request by tonyastolfi**
Hope this helps!  I did a little digging on https://github.com/sile/libflate/issues/52 and was able to get the problem to go away on my local branch.  No idea whether this is the cleanest solution or even technically correct.   Tests all pass with the patch.

---
This change is [Reviewable](https://reviewable.io/reviews/sile/libflate/53)

### CODE REVIEW

**Comment by sile** [comment]
Sorry for the delayed response, and thank you for fixing this bug!
This patch itself seems good but could you add [your code](https://github.com/tonyastolfi/libflate_panic_bug_example) as a test case to prevent future regression?

**Comment by tonyastolfi** [comment]
Thanks for taking a look!  Added the test case, PTAL!

**Review by sile — APPROVED** [review]
Thanks! LGTM!

**Comment by sile** [comment]
Published the fixed version [v1.0.2](https://crates.io/crates/libflate).

**Pull request merged**
